// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB-QIB8fgH6xJjKOSoCyprdqTnC5W6C90',
    appId: '1:224417967621:web:04d1a571bf6180efbe366c',
    messagingSenderId: '224417967621',
    projectId: 'scurd-e749c',
    authDomain: 'scurd-e749c.firebaseapp.com',
    storageBucket: 'scurd-e749c.appspot.com',
    measurementId: 'G-2NZXNZZK4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBwlhrvmYxJlZM6JxXVn9fv7pX6xwA1fk',
    appId: '1:224417967621:android:f0a4d2485edf54cfbe366c',
    messagingSenderId: '224417967621',
    projectId: 'scurd-e749c',
    storageBucket: 'scurd-e749c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz3ERUSIzhr899VJ4G8AeDDVwWfgKrRZU',
    appId: '1:224417967621:ios:97e4631f62a09c7cbe366c',
    messagingSenderId: '224417967621',
    projectId: 'scurd-e749c',
    storageBucket: 'scurd-e749c.appspot.com',
    iosBundleId: 'com.example.sltc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz3ERUSIzhr899VJ4G8AeDDVwWfgKrRZU',
    appId: '1:224417967621:ios:97e4631f62a09c7cbe366c',
    messagingSenderId: '224417967621',
    projectId: 'scurd-e749c',
    storageBucket: 'scurd-e749c.appspot.com',
    iosBundleId: 'com.example.sltc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB-QIB8fgH6xJjKOSoCyprdqTnC5W6C90',
    appId: '1:224417967621:web:cca2d8f509358083be366c',
    messagingSenderId: '224417967621',
    projectId: 'scurd-e749c',
    authDomain: 'scurd-e749c.firebaseapp.com',
    storageBucket: 'scurd-e749c.appspot.com',
    measurementId: 'G-0R5FHTB7EN',
  );
}
